##
## Copyright 2023 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
name: Operator service tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: mydb 
          POSTGRES_PASSWORD: mypass
          POSTGRES_USER: myuser
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup Operator Service 
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master
      - name: Test with pytest
        run: |
          coverage run --source operator_service -m pytest
          coverage report
          coverage xml
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: a750efa066162b16d709e73a9717960a3bc5e9e2c2275a5b2ada6c9eea528123 
